# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df99b059b0382b09490de9db434cf5fc8bcca77a691ae6d416ad72e0af7ebc0b90455bf22503970dd81771ba66ae530a93c9c4713d57f3aab3b8130ebb53b71f

test:
  secret_key_base: bb71be2803b8fdd9201b8133b0c16510120aaefe6f6879a7056ba30da1ae4748f086709ff43cffb5bc5bcd6432fc194d598dde11862f0d513494bd16536b9eca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
